
class BasicTile{
   final String title;
   final List<BasicTile> tiles;

  const BasicTile({
    required this.title,
    this.tiles = const [],
  });

}

final basicTiles = <BasicTile>[
  const BasicTile(title: 'Choose Category',
    tiles: [
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),
      BasicTile(title: 'Grocery',
        tiles: [
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
          BasicTile(title: 'Milk Products',
            tiles: [
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
              BasicTile(title: 'Milk'),
              BasicTile(title: 'Oil'),
              BasicTile(title: 'Salt'),
            ],
          ),
        ],
      ),

    ],
  ),

];
